# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-20 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='posts.Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_subjects',
            field=models.ManyToManyField(to='posts.Subject'),
        ),
    ]
