# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_can_contribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_notificable_by_area',
            field=models.BooleanField(default=False),
        ),
    ]
