# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-21 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170122_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
    ]
