# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-27 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_available_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='available_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
